import meshUtils

pdr = {
       'NH'   : {'ismcpak' : None,
                 'descr'   : 'column density of H',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'H',
                 },              
       'NCO'  : {'ismcpak' : None,
                 'descr'   : 'column density of CO',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'CO',
                 },
       'N13CO': {'ismcpak' : None,
                 'func'    : meshUtils.pdr_mesh_column_density,
                 'descr'   : 'column density of H2',
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : '13CO',
                 },
       'NH2'  : {'ismcpak' : None,
                 'descr'   : 'column density of H2',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'H2',
                 },       
       'NHCN' : {'ismcpak' : None,
                 'descr'   : 'column density of HCN',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'HCN',
                 },       
       'NHNC' : {'ismcpak' : None,
                 'descr'   : 'column density of HNC',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'HNC',
                 },       
       'NHCO+': {'ismcpak' : None,
                 'descr'   : 'column density of HCO+',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'HCO+',
                 },       
       'NCN'  : {'ismcpak' : None,
                 'descr'   : 'column density of CN',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'CN',
                 },       
       'NCS'  : {'ismcpak' : None,
                 'descr'   : 'column density of CS',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'CS',
                 },       
       'NSiO' : {'ismcpak' : None,
                 'descr'   : 'column density of SiO',
                 'func'    : meshUtils.pdr_mesh_column_density,
#                 'latex'   : r'[CII] 158$\mu m$',  
#                 'latex2'  : r'C$^+$ 158$\mum$',
                 'type'    : 'pdr',
                 'specStr' : 'SiO',
                 },       
       }
